### ISSUE TITLE
电视剧搜不到吗？

### ISSUE THREAD

**Issue by rakuyoMo** [Xzonn/JellyfinPluginDouban#1]
电影使用 id 可以搜到，但是电视剧搜不到。比如[来自星星的你](https://movie.douban.com/subject/25698722/) 用 id 25698722 就搜不到。

**Comment by Xzonn** [comment]
谢谢反馈，已修复问题，之后我会发布新版本。

作为临时修复措施，可以在输入框的“名字”那栏填上电视剧的名字。
