### ISSUE TITLE
用豆瓣电影网页后缀ID检索不到封面内容

### ISSUE THREAD

**Issue by X012C** [Xzonn/JellyfinPluginDouban#2]
如题。

**Comment by Xzonn** [comment]
豆瓣的图片域名会限制 Referer，请尝试设置本地反代并在设置中替换图片域名。参考：<https://xzonn.top/posts/Jellyfin-Plugin-Douban.html#%E5%85%B3%E4%BA%8E%E9%80%9F%E7%8E%87%E9%99%90%E5%88%B6>
