### ISSUE TITLE
如果让jellyfin写入nfo文件的话豆瓣信息不会写入

### ISSUE THREAD

**Issue by devome** [Xzonn/JellyfinPluginDouban#3]
安装是当前最新的2.0.2.0，对应jellyfin 10.9.2。如果让jellyfin写入nfo文件的话，用此插件时，豆瓣信息不会写入，之前的opendouban会写入一个`<opendoubanidid>xxxxxx</opendoubanidid>`。

**Comment by Xzonn** [comment]
找到问题了，要写入 `.nfo` 文件需要内部 ID 不能有空格，但是：

https://github.com/Xzonn/JellyfinPluginDouban/blob/160fe632fa53ea75ed9451765961004d17d73372/Jellyfin.Plugin.Douban/Constants.cs#L11

晚上修吧。

**Comment by devome** [comment]
> 找到问题了，要写入 `.nfo` 文件需要内部 ID 不能有空格，但是：
> 
> https://github.com/Xzonn/JellyfinPluginDouban/blob/160fe632fa53ea75ed9451765961004d17d73372/Jellyfin.Plugin.Douban/Constants.cs#L11
> 
> 晚上修吧。

好的，感谢大佬

**Comment by Xzonn** [comment]
应该已经解决了，请更新到 2.1.0.0 版本。旧的 `.nfo` 文件无法自动更新，需要“刷新元数据”→“覆盖所有元数据”。

**Comment by devome** [comment]
是的，action一构建好我就更新用上了，已经解决了。
旧的豆瓣信息我直接用脚本批量修改为了doubanidid，这边就能识别了。
